apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "flink-lineage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flink-lineage.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "services"]
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "delete", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "flink-lineage.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "flink-lineage.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "flink-lineage.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "flink-lineage.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
